// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Menu: typeof import('./src/components/global/cascader/src/menu.vue')['default']
    Node: typeof import('./src/components/global/cascader/src/node.vue')['default']
    Src: typeof import('./src/components/global/cascader/src/index.vue')['default']
    YDydComplexData: typeof import('./src/components/global/formConfig/YDydComplexData.vue')['default']
    YDydComplexInput: typeof import('./src/components/global/formConfig/YDydComplexInput.vue')['default']
    YDydFormCol: typeof import('./src/components/global/formConfig/YDydFormCol.vue')['default']
    YDydFormItem: typeof import('./src/components/global/formConfig/YDydFormItem.vue')['default']
    YDydNumberInput: typeof import('./src/components/global/formConfig/YDydNumberInput.vue')['default']
    YDydRadio: typeof import('./src/components/global/formConfig/YDydRadio.vue')['default']
    YDydSelect: typeof import('./src/components/global/formConfig/YDydSelect.vue')['default']
    YeoForm: typeof import('./src/components/global/form/YeoForm.vue')['default']
  }
}

export { }
